% setup MatConvNet
clear all
clc

rmpath('LibLinear')

run  ../matlab/vl_setupnn

load('HumanPoseModel.mat') ;%%%%%Load the learned Human Pose Model(HPM)
%% Remove the drop-out layers for passing images through the HPM
net.layers{1,23}.type='softmax';
net.layers{1,23
}.name='prob';
net.layers{18}=[];
net.layers{21}=[];
net.layers{18}=net.layers{19};
net.layers{19}=net.layers{20};
net.layers{20}=net.layers{22};
net.layers{21}=net.layers{23};
net.layers(23)=[];
net.layers(22)=[];
%%
list1=dir('data\N-UCLA-Depth\*_e*');
final_features=zeros(4096,length(list1));%%4096 is the size of fc7 outputs vector
labels=zeros(length(list1),4);
for i=1:length(list1)
    list2=dir(['data\N-UCLA-Depth\' list1(i).name '\*.png']);
    sprintf(list1(i).name)
    features=zeros(4096,length(list2));
    for j=1:length(list2)
        ZZ=imread(['data\N-UCLA-Depth\' list1(i).name '\' list2(j).name]);
        tic
        im(:,:,1)=ZZ(:,:,1);
        im(:,:,2)=im(:,:,1);
        im(:,:,3)=im(:,:,1);
        %% Holl filing
        se = strel([1 1 1; 1 1 1; 1 1 1]);
        im=imdilate(im, se);
        %% 
        %%we provided normalized depth images for this dataset. Thus we do not need to normalize them again
        %%
        im_ = single(im) ; % note: 255 range
        im_ = imresize(im_, net.normalization.imageSize(1:2),'bilinear') ;
        im_ = im_ - net.normalization.averageImage ;
        % run the CNN
        res = vl_simplenn(net, im_) ;
        features(:,j) = squeeze(gather(res(20).x)) ;%%%outputs of fc7 layer after ReLU
        elapsedTime(j,1) = toc;
        clear('im')
    end
    %%
    save(['NUCLA-Depth_results\features\' list1(i).name],'features');
    avg_features=mean(features,2);
    final_features(:,i) = avg_features./norm(avg_features,2);
    %%%%%Generate action labels (action,subject,view,iteration)
    action=str2num(list1(i).name(1,2:3));
    subject=str2num(list1(i).name(1,6:7));
    view=str2num(list1(i).name(1,10:11));
    iteration=str2num(list1(i).name(1,14:15));
    labels(i,1:4)=[action subject view iteration];
end
save('NUCLA-Depth_results\final_features_4096','final_features');
save('NUCLA-Depth_results\Labels_4096','labels');
